// Representative glyph per category. Values are either a PoE2 catalog id or a
// verified official CDN URL for PoE1-only categories. Keep this outside the JSX
// component so Node tests and the live canary enforce the same contract.
export const CATEGORY_ICON_IDS = {
  Abyss: "gnawed-jawbone",
  "Atziri's Temple": "architects-orb",
  Breach: "breach-splinter",
  Currency: "exalted",
  Delirium: "simulacrum-splinter",
  Essences: "essence-of-horror",
  Expedition: "expedition-logbook",
  Fragments: "runic-splinter",
  Gems: "ataluis-bloodletting",
  Idols: "bear-idol",
  Ritual: "omen-of-refreshment",
  Runes: "storm-rune",
  "Soul Cores": "soul-core-of-tacati",
  "Uncut Gems": "uncut-skill-gem-20",
  "Needs classification": "exalted",
  Delve: "https://web.poecdn.com/image/Art/2DItems/Currency/Delve/Reroll1x1A.png?scale=1",
  Scarabs: "https://web.poecdn.com/image/Art/2DItems/Currency/Scarabs/LesserScarabBreach.png?scale=1",
  "Divination Cards": "https://web.poecdn.com/image/Art/2DItems/Divination/InventoryIcon.png?scale=1",
  Legion: "https://web.poecdn.com/image/Art/2DItems/Maps/KaruiFragment.png?scale=1",
  Oils: "https://web.poecdn.com/image/Art/2DItems/Currency/Oils/GoldenOil.png?scale=1",
  Catalysts: "https://web.poecdn.com/image/Art/2DItems/Currency/Catalysts/FertileCatalyst.png?scale=1",
  Omens: "omen-of-refreshment",
  Tattoos: "https://web.poecdn.com/image/Art/2DItems/Currency/Ancestors/CommonIntTatttooEquipment.png?scale=1",
  Harvest: "https://web.poecdn.com/image/Art/2DItems/Currency/Harvest/WildLifeforce.png?scale=1",
  Runegrafts: "https://web.poecdn.com/image/Art/2DItems/Currency/Settlers/VillageRune13.png?scale=1",
  Allflame: "https://web.poecdn.com/image/Art/2DItems/Currency/Necropolis/AllflameBetrayal.png?scale=1",
  "Map Fragment": "runic-splinter",
  "Soul Core": "soul-core-of-tacati",
  "Stackable Currency": "exalted",
  "Support Skill Gem": "ataluis-bloodletting",
};
